<?php

namespace App\Domain\Common\Api;

use App\Domain\Common\Brands\Entities\Brand;

class BrandInFilter extends BrandMain
{
    public function toArray()
    {
        $array = parent::toArray(); // TODO: Change the autogenerated stub
        $array["num_product"] = $this->product()->count();
        return $array;
    }
}
