<?php

namespace App\Domain\Installment\Services;

use App\Domain\Core\Main\Entities\Entity;
use App\Domain\Core\Main\Services\BaseService;
use App\Domain\Installment\Entities\CommentInstallment;
use Illuminate\Support\Facades\DB;

class CommentInstallmentService extends BaseService
{

    public function getEntity(): Entity
    {
        return CommentInstallment::new();
    }
    public function create(array $object_data)
    {
        try {

            return parent::create($object_data); // TODO: Change the autogenerated stub
        }catch (\Throwable $exception){
            DB::rollBack();
        }

    }
}
