<?php

namespace App\Domain\Delivery\Entities;

use App\Domain\Core\Language\Traits\Translatable;
use App\Domain\Core\Main\Entities\Entity;
use App\Domain\Delivery\Builders\AvailableCityBuilder;

class AvailableCities extends Entity
{
    use Translatable;

    protected $table = 'available_cities';
    public array $countryName = [];
    public string $countryCode = "";

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->countryName = [
            "ru" => "Узбекистан",
            "en" => "Uzbekistan",
            "uz" => "O`zbekiston"
        ];
        $this->countryCode = "UZ";
    }

    public function newEloquentBuilder($query): AvailableCityBuilder
    {
        return new AvailableCityBuilder($query);
    }


    public function getFullNameAttribute()
    {
        if ($this->id)
            return $this->getRegionNameCurrentAttribute() . " " . $this->getCityNameCurrentAttribute();
    }

    public function setCityNameAttribute($value)
    {
        $this->setTranslate("cityName", $value);
    }

    public function getCityNameAttribute(): ?\Illuminate\Support\Collection
    {
        return $this->getTranslations("cityName");
    }

    public function getCityNameCurrentAttribute(): ?string
    {
        return $this->getTranslatable("cityName");
    }

    public function getRegionNameCurrentAttribute(): ?string
    {
        return $this->getTranslatable("regionName");
    }

    public function getRegionNameAttribute(): ?\Illuminate\Support\Collection
    {
        return $this->getTranslations("regionName");
    }

    public function setRegionNameAttribute($value)
    {
        $this->setTranslate("regionName", $value);
    }

    public function toArray()
    {
        $object = parent::toArray(); // TODO: Change the autogenerated stub
        $object['region'] = $this->getRegionNameAttribute()['ru'];
        $object['countryName'] = $this->countryName['ru'];
        $object['city'] = $this->getCityNameCurrentAttribute();
        unset($object['cityName']);
        return $object;
    }
}
