<?php

namespace App\Http\Controllers\Base\Abstracts;

use Illuminate\Foundation\Http\FormRequest;

abstract class BaseNestedController extends BaseController
{
    public function create($request)
    {
        parent::create($request); // TODO: Change the autogenerated stub
    }
}
