<?php

namespace App\Domain\Order\Services;

use App\Domain\Core\Main\Entities\Entity;
use App\Domain\Core\Main\Services\BaseService;
use App\Domain\Delivery\Services\DeliveryAddressService;
use App\Domain\Delivery\Services\DeliverySendService;
use App\Domain\Installment\Interfaces\PurchaseRelationInterface;
use App\Domain\Order\Entities\Purchase;
use App\Domain\Order\Entities\UserPurchase;
use App\Domain\Order\Interfaces\UserOrderInterface;
use App\Domain\Order\Interfaces\UserPurchaseRelation;
use App\Domain\Product\Product\Entities\Product;
use App\Domain\Telegrams\Job\TelegramJob;
use Illuminate\Support\Facades\DB;

class UserPurchaseService extends BaseService implements UserPurchaseRelation
{
    private PurchaseService $purchaseService;
    private DeliveryAddressService $deliveryAddressService;

    public function __construct()
    {
        $this->purchaseService = new PurchaseService();
        $this->deliveryAddressService = new DeliveryAddressService();
        parent::__construct();
    }

    private function toPurchases(array &$object_data)
    {
        if (isset($object_data[self::PURCHASE_SERVICE])) {
            return $object_data[self::PURCHASE_SERVICE];
        }
        if (isset($object_data[self::PRODUCTS_ENCODE])) {
            $product = json_decode($object_data[self::PRODUCTS_ENCODE], true);
            unset($object_data[self::PRODUCTS_ENCODE]);
            $purchases = [];
            foreach ($product as $id => $number) {
                $real_product = Product::find($id);
                $uzs_price = $real_product->real_price;
                if ($real_product->number >= $number)
                    array_push($purchases, [
                        'quantity' => $number,
                        'price' => $uzs_price * $number,
                        'product_id' => $id,
                        "order" => json_encode("", JSON_UNESCAPED_UNICODE)
                    ]);
                else
                    throw new \Exception(
                        __("Количество превосходит доступного для продукта")
                        . sprintf(" %s .", $product->title_current)
                        . __("Всего иметься") . sprintf(": %s .", $real_product->number) .
                        __("Заказано") . sprintf(": %s .", $number)
                    );
            }
            return $purchases;
        }
    }

    private function getStatus(array &$object_data): int
    {
        $status = UserOrderInterface::INSTALMENT;
        if (array_key_exists("delivery", $object_data)) {
            $status += UserOrderInterface::DELIVERY;
        } else {
            $status += UserOrderInterface::SELF_DELIVERY;
        }
        unset($object_data['delivery']);

        return $status;
    }

    public function getEntity(): Entity
    {
        return new UserPurchase();
    }

    public function create(array $object_data): UserPurchase
    {
        try {
            DB::beginTransaction();
            $object_data['status'] = $this->getStatus($object_data);
            $purchase = $this->popCondition($object_data, PurchaseRelationInterface::PURCHASE_SERVICE);

            $object = parent::create($object_data);
            if ($object->isDelivery()) {
                $delivery = $this->popCondition($purchase, self::DELIVERY_ADDRESS_SERVICE);
                $delivery_object = $this->deliveryAddressService->create($delivery);
                $object->address()->attach($delivery_object->id);
            }
            $purchases = $this->toPurchases($object_data);
            $object->purchases()->createMany($purchases);
            DB::commit();
            return $object;
        } catch (\Throwable $exception) {
            DB::rollBack();
            throw  $exception;
        }

    }

    public function update($object, array $object_data)
    {
        return parent::update($object, $object_data); // TODO: Change the autogenerated stub
    }
}
