<?php

namespace App\Domain\Core\Front\Admin\Form\Attributes\Models;

use App\Domain\Core\File\Models\Livewire\FileLivewireFactoring;
use App\Domain\Core\Front\Admin\Attributes\Containers\NestedContainer;
use App\Domain\Core\Front\Admin\Templates\Models\BladeGenerator;

class ComplexAttribute extends BladeGenerator
{
    public string $title;

    protected function __construct($title, array $items)
    {
        $this->title = $title;
        parent::__construct($items);
    }

    public static function generation(array $items, string $title = ""): BladeGenerator
    {
        return new self($title, $items); // TODO: Change the autogenerated stub
    }

    public function generateHtml(): string
    {
        return NestedContainer::new($this->title, $this->items);
    }
}
