<?php

namespace App\Domain\User\Services;

use App\Domain\User\Interfaces\Roles;
use App\Domain\User\Interfaces\UserRelationInterface;

class AdminService extends AbstractUserService
{
    protected function createRole($object_data, $user)
    {
        $role = $this->popCondition($object_data, UserRelationInterface::ROLE_SERVICE);
        $this->role->create([
            'user_id' => $user->id,
            'role' => $role['role']
        ]);
    }

    function getRole(): int
    {
        return Roles::ADMIN;
    }

    public function update($object, array $object_data)
    {
        $role = $this->popCondition($object_data, UserRelationInterface::ROLE_SERVICE);
        $this->role->update($object->role()->first(), $role);
        return parent::update($object, $object_data); // TODO: Change the autogenerated stub
    }
}
