<?php

namespace App\Domain\User\Services;

use App\Domain\Core\Main\Entities\Entity;
use App\Domain\Core\Main\Services\BaseService;
use App\Domain\User\Entities\PlasticCard;

class PlasticCardService extends BaseService
{
    public function getEntity(): Entity
    {
        return new PlasticCard();
    }
    public function create(array $object_data)
    {
        dd($object_data);
//        return parent::create($object_data); // TODO: Change the autogenerated stub
    }
}
