<?php

namespace App\Domain\User\Services;

use App\Domain\Core\Api\CardService\BindCard\Model\BindCardService;
use App\Domain\Core\Main\Entities\Entity;
use App\Domain\Core\Main\Services\BaseService;
use App\Domain\User\Entities\PlasticCard;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class PlasticCardService extends BaseService
{
    public function getEntity(): Entity
    {
        return new PlasticCard();
    }

    public function create(array $object_data)
    {
        try {
            DB::beginTransaction();
            $service = new BindCardService();
            $result = $service->apply($object_data["transaction_id"], $object_data['code']);
            $object_data = array_merge($object_data, $result['data']);
            parent::create($object_data);
            DB::commit();
        } catch (\Exception $exception) {
            DB::rollBack();
            throw ValidationException::withMessages([
                "message" => $exception->getMessage()
            ]);
        }
//        return parent::create($object_data); // TODO: Change the autogenerated stub
    }
}
