<?php

namespace App\Domain\User\Services;

use App\Domain\Core\Main\Services\BaseService;
use App\Domain\User\Entities\User;
use App\Domain\User\Traits\PasswordHandle;

class UserService extends BaseService
{
    use  PasswordHandle;

    public function getEntity(): User
    {
        return new User();
    }

    public function create(array $object_data)
    {
        $this->updatePassword($object_data);
        return parent::create($object_data); // TODO: Change the autogenerated stub
    }

    public function update($object, array $object_data): \App\Domain\Core\Main\Entities\Entity
    {
        $this->updatePassword($object_data);
        return parent::update($object, $object_data); // TODO: Change the autogenerated stub
    }
}
