<?php

namespace App\Domain\Common\Colors\Services;

use App\Domain\Common\Colors\Entities\Color;
use App\Domain\Core\Main\Entities\Entity;
use App\Domain\Core\Main\Services\BaseService;

class ColorService extends BaseService
{
    public function getEntity(): Entity
    {
        return  new Color();
    }
    public function create(array $object_data)
    {
        dd($object_data);
        return parent::create($object_data); // TODO: Change the autogenerated stub
    }
}
