<?php

namespace App\Domain\Installment\Front\Admin\CustomTables\Tables;

use App\Domain\Core\Front\Admin\Attributes\Models\Column;
use App\Domain\Core\Front\Admin\CustomTable\Abstracts\AbstractTable;
use App\Domain\Core\Front\Admin\CustomTable\Abstracts\BaseTable;

class MonthlyPaidTable extends BaseTable
{

    public function getColumns(): array
    {
        return [
            Column::new(__("Месяц"), "month_index"),
            Column::new(__("Оплата"), "paid_index"),
            Column::new(__("Статус"), "status_index")
        ];
    }

    public function generateHtml(): string
    {
        return parent::generateHtml(); // TODO: Change the autogenerated stub
    }
}
