<?php

namespace App\Domain\Core\Front\Admin\Button\ModelInCompelationTime;

use App\Domain\Core\Front\Admin\Button\Traits\GenerateTagAttributes;

class GrayButtonCompile extends BaseButtonCompile
{
    use GenerateTagAttributes;
    static public function new($name, $attributes = [])
    {
        $standard = [
            'class' => "bg-gray-600 hover:bg-gray-400"
        ];
        return parent::new($name, self::append($standard, $attributes)); // TODO: Change the autogenerated stub
    }
}
