<?php

namespace App\Domain\Product\ProductKey\Builders;

use App\Domain\Core\Main\Builders\BuilderEntity;

class ProductKeyBuilder extends BuilderEntity
{

    protected function getSearch(): string
    {
        return "text";
    }

    public function joinFiltration()
    {
        return $this->join("filtration_key_category", "filtration_key_category.product_key_id",
            "=", "product_keys.id");
    }

    public function filterBy($filter): ProductKeyBuilder
    {
        if (isset($filter['category_id'])) {
            $this->joinFiltration()->where(
                "filtration_key_category.category_id",
                "=", $filter['category_id']);
        }
        return parent::filterBy($filter); // TODO: Change the autogenerated stub
    }
}
