<?php

namespace App\Domain\Product\ProductKey\Builders;

use App\Domain\Core\Main\Builders\BuilderEntity;

class ProductValueBuilder extends BuilderEntity
{
    protected function getSearch(): string
    {
        return "text";
    }

    public function filterBy($filter)
    {
        if (isset($filter['product_key_id'])) {
            $this->where("product_key_id" , "=", $filter['product_key_id']);
        }
        return parent::filterBy($filter); // TODO: Change the autogenerated stub
    }
}
